### ISSUE TITLE
Add screenshot in README

### ISSUE THREAD

**Issue by uilianries** [GDGVIT/ConanGUI#7]
As a graphical tool, users want to see how the interface looks like before installing.

**Comment by L04DB4L4NC3R** [comment]
@Roidujeu it is a good idea to add screenshots of both light and dark mode in the README

**Comment by Roidujeu** [comment]
Screenshots have been added. Please close this issue.

**Comment by L04DB4L4NC3R** [comment]
Added in #8 . Closing this issue
